package application.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

public class PrincipalController {
	@FXML
	private TextField tfCodigoFuncionario;
	@FXML
	private TextField tfNomeFuncionario;
	@FXML
	private TextField idadeFuncionario;
	@FXML
	private Button bpnBuscarFuncionario;
	@FXML
	private Button bpnInserirFuncionario;
	@FXML
	private Button bpnAtualizarFuncionario;
	@FXML
	private Button bpnExcluirFuncionario;
	@FXML
	private Button bpnListarFuncionario;
	@FXML
	private TextArea taListaFuncionario;
	@FXML
	private Button bpnCopiaFuncionario;
	@FXML
	private TextField tfCodigoPessoa;
	@FXML
	private TextField tfNomePessoa;
	@FXML
	private TextField idadePessoa;
	@FXML
	private Button bpnBuscarPessoa;
	@FXML
	private Button bpnInserirPessoa;
	@FXML
	private Button bpnAtualizarPessoa;
	@FXML
	private Button bpnExcluirPessoa;
	@FXML
	private Button bpnListarPessoa;
	@FXML
	private TextArea taListaPessoa;
	@FXML
	private Button bpnCopiaPessoa;
	@FXML
	private TextField tfCodigoEntregador;
	@FXML
	private TextField tfNomeEntregador;
	@FXML
	private Button bpnInserirEntregador;
	@FXML
	private Button bpnAtualizarEntregador;
	@FXML
	private Button bpnExcluirEntregador;
	@FXML
	private Button bpnListarEntregador;
	@FXML
	private TextArea taListaEntregador;
	@FXML
	private TextField tfCodigoPizzaSalgada;
	@FXML
	private TextField tfNomePizzaSalgada;
	@FXML
	private Button bpnInserirPizzaSalgada;
	@FXML
	private Button bpnAtualizarPizzaSalgada;
	@FXML
	private Button bpnExcluirPizzaSalgada;
	@FXML
	private Button bpnListarPizzaSalgada;
	@FXML
	private TextArea taListaPizzaSalgada;
	@FXML
	private TextField tfCodigoPizzaDoce;
	@FXML
	private TextField tfNomePizzaDoce;
	@FXML
	private Button bpnInserirPizzaDoce;
	@FXML
	private Button bpnAtualizarPizzaDoce;
	@FXML
	private Button bpnExcluirPizzaDoce;
	@FXML
	private Button bpnListarPizzaDoce;
	@FXML
	private TextArea taListaPizzaDoce;
	@FXML
	private Button bpnInserirPagamento;
	@FXML
	private Button bpnAtualizarPagamento;
	@FXML
	private Button bpnExcluirPagamento;
	@FXML
	private Button bpnListarPagamento;
	@FXML
	private TextArea taListaPagamento;

	// Event Listener on TextField[#tfCodigoFuncionario].onAction
	@FXML
	public void acaoFuncionario(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on TextField[#tfCodigoPessoa].onAction
	@FXML
	public void acaoPessoa(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bpnCop�aPessoa].onAction
	@FXML
	public void copiaPessoa(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#tfCodigoEntregador].onAction
	@FXML
	public void acaoEntregador(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#tfCodigoPizzaSalgada].onAction
	@FXML
	public void acaoPizzaSalgada(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#tfCodigoPizzaDoce].onAction
	@FXML
	public void acaoPizzaDoce(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bpnInserirPagamento].onAction
	@FXML
	public void acaoPagamento(ActionEvent event) {
		// TODO Autogenerated
	}
}
